POST http://localhost:8000/categories/
Content-Type: application/json

{
    "name": "some_name"
}

###
GET http://localhost:8000/categories/
Content-Type: application/json

{
    
}
###
GET http://localhost:8000/categories/d3bd4665-25b4-4b13-adf4-e6bacf16e6cd
